run:
  tests: true
  skip-dirs:
    - bin

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - errcheck
    - gosimple
    - lll
    - goerr113
    - paralleltest